name: jupyter_slides

channels:
  - conda-forge
  - damianavila82

dependencies:
  - python=3.6
  - jupyterlab
  - pandas
  - matplotlib
  - scikit-learn
  - ipywidgets
  - beakerx       # interactive tables + lots more
  - xlrd          # read XLSX files
#  - xlwings       # bi-directional integration with Excel - only works on local machine
  - bokeh
  - seaborn       # beautiful statistical plots
  - plotly        # interactive plotting
  - ipyleaflet    # maps
  - ua-parser
  - rise          # live slideshows
  - bqplot
  - pip:
    - cufflinks   # plotly and pandas integration
